### PR TITLE
Introduction to Triage Party for area/conformance

### PR DESCRIPTION
**Pull request by heyste**
Document covers

-  Triage Party use case for [triageparty.apisnoop.io](http://triageparty.apisnoop.io/)
- What's been customized?
- Configuration: `k8s-area-conformance-triage-party.yaml`

### CODE REVIEW

**Comment by hh** [comment]
I wouldn't create an org-block for the sake of creating an org-block.

You can use `file:party.yaml` to reference the file via a link from the org file.

Otherwise your just duplicating the effort / commit size without the org-file adding metadata / value around that file.

**Comment by hh** [comment]
In addition to the configuration file for triage-party itself, do you have the k8s manifest / deploy itself?

**Comment by heyste** [comment]
Condensed [configuration section](https://github.com/cncf/apisnoop/blob/triage-party/docs/checking-conformance-progress-with-triage-party.org#configuration)

**Comment by hh** [comment]
Great work @heyste !

**Pull request merged**
