### PR TITLE
Useful filters

### PR DESCRIPTION
**Pull request by zachmandeville**
This PR adds a list of useful filters to the sidebar.  it is based on #229  and #256

### CODE REVIEW

**Comment by dankohn** [comment]
Please change "Kube" to "K8s"

**Comment by devaips** [comment]
Checking the deploy-preview, there appears to be a bug where when clicking the links the user-agent filter sometimes persists even when switching to a filter with a new user-agent.

Please see if you can reproduce @zachmandeville

**Comment by zachmandeville** [comment]
I see what you mean, @devaips  and can reproduce.  I just pushed a commit, https://github.com/cncf/apisnoop/pull/263/commits/ea5173d9e2fc965f50aa8bc950401e569d105d3a,  to make the filters more explicit and correct this behavior.

**Pull request merged**
