### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by haardikdharma10**

### CODE REVIEW

**Comment by Riaankl** [comment]
@haardikdharma10 
Thank you for the document review.
The broken link to the Readme still do not work. Please consider this link:
https://github.com/cncf/apisnoop/blob/master/README.org

While reviewing the document I noticed that the title is also not displaying correctly due to a unnecessary space before #+TITLE: Set up with Kubemacs.  Will you update that as well?

**Comment by haardikdharma10** [comment]
Fixed the link. Didn't get the title part though. In all the other docs the title is written in the same format!?

**Comment by Riaankl** [comment]
Please delete the extra space where the red dot is in the picture to make the title display correct. Save making another PR just for that.
image

**Comment by haardikdharma10** [comment]
@Riaankl, done! Please have a look.

**Comment by Riaankl** [comment]
@haardikdharma10 
Good job. Thank you for supporting our community's work.

**Comment by haardikdharma10** [comment]
My pleasure.

**Pull request merged**
