### PR TITLE
Add WIP ReplicationController lifecycle test - +7 test endpoint coverage

### PR DESCRIPTION
**Pull request by BobyMCbobs**
- [x] mock ticket: #
- [x] issue created: https://github.com/kubernetes/kubernetes/issues/88302
- [ ] PR created: XX
- [ ] Promotion Created: XX

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
Having issues trying to hit the endpoint `readCoreV1NamespacedReplicationControllerStatus` with the following code:
```go
       rcStatusUnstructured, err := DynamicClientSet.Resource(rcResource).Namespace(testRcNamespace).Get(testRcName, metav1.GetOptions{}, "status")
       if err != nil {
           fmt.Println(err)
           return
       }
       fmt.Println(rcStatusUnstructured)
       fmt.Println("[status] fetched ReplicationController status")
```

The error `the server could not find the requested resource` keeps returning.

**Comment by BobyMCbobs** [comment]
> Having issues trying to hit the endpoint `readCoreV1NamespacedReplicationControllerStatus` with the following code:
> 
> ```go
>        rcStatusUnstructured, err := DynamicClientSet.Resource(rcResource).Namespace(testRcNamespace).Get(testRcName, metav1.GetOptions{}, "status")
>        if err != nil {
>            fmt.Println(err)
>            return
>        }
>        fmt.Println(rcStatusUnstructured)
>        fmt.Println("[status] fetched ReplicationController status")
> ```
> 
> The error `the server could not find the requested resource` keeps returning.

The ReplicationController resource schema was incorrect, updated to be
```
       rcResource := schema.GroupVersionResource{Group: "", Version: "v1", Resource: "replicationcontrollers"}
```

**Comment by hh** [comment]
Tempted to have the '.org' files be accompanied by an exported `.md`

**Comment by hh** [comment]
@BobyMCbobs can you put this at the top

- [x] issue created: https://github.com/kubernetes/kubernetes/issues/88302
- [ ] PR created: XX
- [ ] Promotion Created: XX

**Pull request merged**
