### PR TITLE
Add WIP ServiceAccount Resource Lifecycle test

### PR DESCRIPTION
**Pull request by BobyMCbobs**
- [x] [mock ticket](#)
- [x] [issue created](https://github.com/kubernetes/kubernetes/issues/89071)
- [x] [PR created](https://github.com/kubernetes/kubernetes/pull/90193)
- [ ] Promotion created

endpoints hit: 3

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
Unsure if in the test a Pod with the ServiceAccount assigned should be created after the ServiceAccount is, then after the patch create a new Pod to ensure that ServiceAccount contains the secret (perhaps as env)

**Comment by BobyMCbobs** [comment]
> Unsure if in the test:
> a Pod with the ServiceAccount assigned should be created after the ServiceAccount is, then after the patch create a new Pod to ensure that ServiceAccount contains the secret (perhaps as env)

Would be too much code, without using framework

**Comment by BobyMCbobs** [comment]
Possibly should add `createCoreV1NamespacedServiceAccountToken` endpoint to this test

**Comment by BobyMCbobs** [comment]
> Possibly should add `createCoreV1NamespacedServiceAccountToken` endpoint to this test

Attempting to implement it with:
```golang
       fmt.Println("creating a ServiceAccountToken")
       tokenExpirySeconds := int64(10000)
       serviceAccountToken := authenticationv1.TokenRequest{
           Spec: authenticationv1.TokenRequestSpec{
               ExpirationSeconds: &tokenExpirySeconds,
               Audiences: []string{"api"},
           //    BoundObjectRef: &authenticationv1.BoundObjectReference{
           //        Kind:       "Secret",
           //        APIVersion: "v1",
           //        Name:       testSecretGet.Name,
           //        UID:        testSecretGet.UID,
           //    },
           },
       }
       tokenRequest, err := ClientSet.CoreV1().ServiceAccounts(testNamespaceName).CreateToken(testServiceAccountName, &serviceAccountToken)
       if err != nil {
          fmt.Println(err, "failed to create the ServiceAccountToken")
          return
       }
       if tokenRequest.Status.Token == "" {
          fmt.Println("failed to create the ServiceAccountToken")
       }
```

results in:
```
the server could not find the requested resource failed to create the ServiceAccountToken
```

**Comment by BobyMCbobs** [comment]
WIP Patch for adding token creation
```
diff --git a/org/tickets/CoreV1ServiceAccountResourceLifecycleTest.org b/org/tickets/CoreV1ServiceAccountResourceLifecycleTest.org
index 7b048cb..07b3a8d 100644
--- a/org/tickets/CoreV1ServiceAccountResourceLifecycleTest.org
+++ b/org/tickets/CoreV1ServiceAccountResourceLifecycleTest.org
@@ -173,6 +173,7 @@ According to this APIsnoop query, there are still some remaining ServiceAccount
 
        testNamespaceName := "default"
        testServiceAccountName := "testserviceaccount"
+       // testServiceAccountTokenName := fmt.Sprintf("%v-token", testServiceAccountName)
        testSecretName := "testsecret"
 
        fmt.Println("creating a ServiceAccount")
@@ -184,8 +185,19 @@ According to this APIsnoop query, there are still some remaining ServiceAccount
        }
        _, err = ClientSet.CoreV1().ServiceAccounts(testNamespaceName).Create(&testServiceAccount)
        if err != nil {
-          fmt.Println(err, "failed to create a ServiceAccount")
-          return
+           fmt.Println(err, "failed to create a ServiceAccount")
+           return
+       }
+       saWatch, err := ClientSet.CoreV1().ServiceAccounts(testNamespaceName).Watch(metav1.ListOptions{LabelSelector: "test-serviceaccount-static=true"})
+       if err != nil {
+           fmt.Println(err, "failed to create a watch for the ServiceAccount")
+           return
+       }
+       saWatchChan := saWatch.ResultChan()
+       for event := range saWatchChan {
+           if event.Type == "ADDED" {
+               break
+           }
        }
 
        fmt.Println("creating a Secret")
@@ -225,14 +237,24 @@ According to this APIsnoop query, there are still some remaining ServiceAccount
        serviceAccountToken := authenticationv1.TokenRequest{
            Spec: authenticationv1.TokenRequestSpec{
                ExpirationSeconds: &tokenExpirySeconds,
-	             Audiences: []string{testServiceAccountName},
+               Audiences: []string{"api"},
+           //    BoundObjectRef: &authenticationv1.BoundObjectReference{
+           //        Kind:       "Secret",
+           //        APIVersion: "v1",
+           //        Name:       testSecretGet.Name,
+           //        UID:        testSecretGet.UID,
+           //    },
            },
        }
-       _, err = ClientSet.CoreV1().ServiceAccounts(testNamespaceName).CreateToken(testServiceAccountName, &serviceAccountToken)
+       tokenRequest, err := ClientSet.CoreV1().ServiceAccounts(testNamespaceName).CreateToken(testServiceAccountName, &serviceAccountToken)
        if err != nil {
           fmt.Println(err, "failed to create the ServiceAccountToken")
           return
        }
+       if tokenRequest.Status.Token == "" {
+          fmt.Println("failed to create the ServiceAccountToken")
+	        return
+       }
 
        fmt.Println("finding ServiceAccount in list of all ServiceAccounts (by LabelSelector)")
        serviceAccountList, err := ClientSet.CoreV1().ServiceAccounts("").List(metav1.ListOptions{LabelSelector: "test-serviceaccount-static=true"})
```

**Comment by hh** [comment]
We are going to merge often or test writing workflow tickets and pointing to the org/status files directly instead.

**Pull request merged**
